/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedAssinaturasRouteImport } from './routes/_authenticated/assinaturas'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedAutomacoesRouteImport } from './routes/_authenticated/automacoes'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedEmailRouteImport } from './routes/_authenticated/email'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedEtiquetasRouteImport } from './routes/_authenticated/etiquetas'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedIaRouteImport } from './routes/_authenticated/ia'
import { Route as AuthenticatedIntegracoesRouteImport } from './routes/_authenticated/integracoes'
import { Route as AuthenticatedMapaRouteImport } from './routes/_authenticated/mapa'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedPropostasRouteImport } from './routes/_authenticated/propostas'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedVisitasRouteImport } from './routes/_authenticated/visitas'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AssinarTokenRouteImport } from './routes/assinar.$token'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads.index'
import { Route as AuthenticatedLeadsIdRouteImport } from './routes/_authenticated/leads.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssinaturasRoute =
  AuthenticatedAssinaturasRouteImport.update({
    id: '/assinaturas',
    path: '/assinaturas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomacoesRoute = AuthenticatedAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailRoute = AuthenticatedEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEtiquetasRoute = AuthenticatedEtiquetasRouteImport.update({
  id: '/etiquetas',
  path: '/etiquetas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIaRoute = AuthenticatedIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegracoesRoute =
  AuthenticatedIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMapaRoute = AuthenticatedMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropostasRoute = AuthenticatedPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisitasRoute = AuthenticatedVisitasRouteImport.update({
  id: '/visitas',
  path: '/visitas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AssinarTokenRoute = AssinarTokenRouteImport.update({
  id: '/assinar/$token',
  path: '/assinar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsIdRoute = AuthenticatedLeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/assinaturas': typeof AuthenticatedAssinaturasRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/email': typeof AuthenticatedEmailRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/etiquetas': typeof AuthenticatedEtiquetasRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/ia': typeof AuthenticatedIaRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/propostas': typeof AuthenticatedPropostasRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/visitas': typeof AuthenticatedVisitasRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/assinar/$token': typeof AssinarTokenRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/assinaturas': typeof AuthenticatedAssinaturasRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/email': typeof AuthenticatedEmailRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/etiquetas': typeof AuthenticatedEtiquetasRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/ia': typeof AuthenticatedIaRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/propostas': typeof AuthenticatedPropostasRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/visitas': typeof AuthenticatedVisitasRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/assinar/$token': typeof AssinarTokenRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/assinaturas': typeof AuthenticatedAssinaturasRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/automacoes': typeof AuthenticatedAutomacoesRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/email': typeof AuthenticatedEmailRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRoute
  '/_authenticated/etiquetas': typeof AuthenticatedEtiquetasRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/ia': typeof AuthenticatedIaRoute
  '/_authenticated/integracoes': typeof AuthenticatedIntegracoesRoute
  '/_authenticated/mapa': typeof AuthenticatedMapaRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/propostas': typeof AuthenticatedPropostasRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/_authenticated/visitas': typeof AuthenticatedVisitasRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/assinar/$token': typeof AssinarTokenRoute
  '/_authenticated/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/agenda'
    | '/assinaturas'
    | '/auditoria'
    | '/automacoes'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/documentos'
    | '/email'
    | '/empresas'
    | '/etiquetas'
    | '/financeiro'
    | '/ia'
    | '/integracoes'
    | '/mapa'
    | '/pipeline'
    | '/propostas'
    | '/ranking'
    | '/relatorios'
    | '/tarefas'
    | '/visitas'
    | '/whatsapp'
    | '/assinar/$token'
    | '/leads/$id'
    | '/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/agenda'
    | '/assinaturas'
    | '/auditoria'
    | '/automacoes'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/documentos'
    | '/email'
    | '/empresas'
    | '/etiquetas'
    | '/financeiro'
    | '/ia'
    | '/integracoes'
    | '/mapa'
    | '/pipeline'
    | '/propostas'
    | '/ranking'
    | '/relatorios'
    | '/tarefas'
    | '/visitas'
    | '/whatsapp'
    | '/assinar/$token'
    | '/leads/$id'
    | '/leads'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/agenda'
    | '/_authenticated/assinaturas'
    | '/_authenticated/auditoria'
    | '/_authenticated/automacoes'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentos'
    | '/_authenticated/email'
    | '/_authenticated/empresas'
    | '/_authenticated/etiquetas'
    | '/_authenticated/financeiro'
    | '/_authenticated/ia'
    | '/_authenticated/integracoes'
    | '/_authenticated/mapa'
    | '/_authenticated/pipeline'
    | '/_authenticated/propostas'
    | '/_authenticated/ranking'
    | '/_authenticated/relatorios'
    | '/_authenticated/tarefas'
    | '/_authenticated/visitas'
    | '/_authenticated/whatsapp'
    | '/assinar/$token'
    | '/_authenticated/leads/$id'
    | '/_authenticated/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AssinarTokenRoute: typeof AssinarTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assinaturas': {
      id: '/_authenticated/assinaturas'
      path: '/assinaturas'
      fullPath: '/assinaturas'
      preLoaderRoute: typeof AuthenticatedAssinaturasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automacoes': {
      id: '/_authenticated/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AuthenticatedAutomacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email': {
      id: '/_authenticated/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof AuthenticatedEmailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/etiquetas': {
      id: '/_authenticated/etiquetas'
      path: '/etiquetas'
      fullPath: '/etiquetas'
      preLoaderRoute: typeof AuthenticatedEtiquetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ia': {
      id: '/_authenticated/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof AuthenticatedIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integracoes': {
      id: '/_authenticated/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AuthenticatedIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapa': {
      id: '/_authenticated/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AuthenticatedMapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/propostas': {
      id: '/_authenticated/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof AuthenticatedPropostasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visitas': {
      id: '/_authenticated/visitas'
      path: '/visitas'
      fullPath: '/visitas'
      preLoaderRoute: typeof AuthenticatedVisitasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/assinar/$token': {
      id: '/assinar/$token'
      path: '/assinar/$token'
      fullPath: '/assinar/$token'
      preLoaderRoute: typeof AssinarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/$id': {
      id: '/_authenticated/leads/$id'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AuthenticatedLeadsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAssinaturasRoute: typeof AuthenticatedAssinaturasRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedAutomacoesRoute: typeof AuthenticatedAutomacoesRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedEmailRoute: typeof AuthenticatedEmailRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRoute
  AuthenticatedEtiquetasRoute: typeof AuthenticatedEtiquetasRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedIaRoute: typeof AuthenticatedIaRoute
  AuthenticatedIntegracoesRoute: typeof AuthenticatedIntegracoesRoute
  AuthenticatedMapaRoute: typeof AuthenticatedMapaRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedPropostasRoute: typeof AuthenticatedPropostasRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
  AuthenticatedVisitasRoute: typeof AuthenticatedVisitasRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
  AuthenticatedLeadsIdRoute: typeof AuthenticatedLeadsIdRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAssinaturasRoute: AuthenticatedAssinaturasRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedAutomacoesRoute: AuthenticatedAutomacoesRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedEmailRoute: AuthenticatedEmailRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRoute,
  AuthenticatedEtiquetasRoute: AuthenticatedEtiquetasRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedIaRoute: AuthenticatedIaRoute,
  AuthenticatedIntegracoesRoute: AuthenticatedIntegracoesRoute,
  AuthenticatedMapaRoute: AuthenticatedMapaRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedPropostasRoute: AuthenticatedPropostasRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
  AuthenticatedVisitasRoute: AuthenticatedVisitasRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
  AuthenticatedLeadsIdRoute: AuthenticatedLeadsIdRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AssinarTokenRoute: AssinarTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
